# Node version to use  
FROM node:18-alpine

# Set working directory
WORKDIR /react-vite-build

# Copy package.json and package-lock.json to container 
COPY package*.json /react-vite-build

# Install dependencies 
RUN npm install 

# Copy everything from our local dir to the container image dir
COPY . /react-vite-build/

# Prod build
RUN npm run build 

# Port 80 exposed
EXPOSE 80

CMD ["npm", "run", "dev"]









